application: ${PROJECT_ID}
version: 1
runtime: go
api_version: go1.9

handlers:
- url: /.*
  script: _go_app

- url: /static
  static_dir: static

- url: /
  static_files: static/index.html
  upload: static/index.html

env_variables:
  SOMETHING: FOO
